name: Basic Github Actions YAML

on:
  workflow_dispatch:

jobs:    
  testing:
    name: Testing Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: List Files
        run: |
                echo "I am listing files now"
                ls
                
                echo "Whats inside index.html?"

                cat index.html