name : Basic GitHub Actions for Cowsay

on:
  push:

jobs:
  asciijob:
    name: Working with cowsay
    runs-on: ubuntu-latest
    steps:
      - name: Installing cowsay command
        run: sudo apt-get install -y cowsay
      - name: running cowsay command
        run: cowsay -f dragon "This must be a dragon" >> dragon.txt
      - name: Read the file
        run: |
                cat dragon.txt
                grep -i dragon dragon.txt
                ls -la
  
  test-job:
    name: Testing the file
    runs-on: ubuntu-latest
    steps:
    - name: read the file
      run: |
            echo "read the file again"
            cat dragon.txt