name : Basic GitHub Actions for Cowsay

on:
  push:

jobs:
  asciijob:
    name: Working with cowsay
    runs-on: ubuntu-latest
    steps:
      - name: Installing cowsay command
        run: sudo apt-get install -y cowsay
      - name: running cowsay command
        run: cowsay -f dragon "This must be a dragon" >> dragon.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dragon-file-text
          path: dragon.txt
  
  test-job:
    name: Testing the file
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: dragon-file-text
    - name: read the file
      run: |
            echo "read the file again"
            cat dragon.txt