name: Exploring Varibales and Secrets

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: step level env
        env:
          DOCKER_USERNAME: arjun1891
        run: echo docker build -t docker.io/$DOCKER_USERNAME/webimg
      - run: echo docker login --username: $DOCKER_USERNAME --password=querty
