name: Exploring Varibales and Secrets

on:
  workflow_dispatch:
env:
  DOCKER_USERNAME: arjun1891
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: step level env
        run: echo docker build -t ${{ vars.DOCKER_URL }}/${{ env.DOCKER_USERNAME }}/webimg
      - run: echo docker login --username=${{ env.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASS }}
